version: '3.8'
services:
  api1:
    image: ferrugem_rust:latest
    environment:
      DATABASE_URL: postgres://postgres:999@db:5432/postgres?schema=public&sslmode=disable
      MAX_DB_CONNECTIONS: 3
      KEEPALIVE_DURATION: 2
      DB_POOL_TIMEOUT: 58000
      PORT: 3000
    depends_on:
      - db
    expose:
      - "3000"
    ports:
      # For diagnosing
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.11'
          memory: '6MB'

  api2:
    image: ferrugem_rust:latest
    environment:
      DATABASE_URL: postgres://postgres:999@db:5432/postgres?schema=public&sslmode=disable
      MAX_DB_CONNECTIONS: 3
      KEEPALIVE_DURATION: 2
      DB_POOL_TIMEOUT: 58000
      PORT: 3000
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.11'
          memory: '6MB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.18'
          memory: '38MB'
  
  # Banco postgres
  db:
    image: postgres:16
    hostname: db
    environment:
      - POSTGRES_PASSWORD=999
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432" # Exposing is useful for debugging. 
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    deploy:
      resources:
        limits:
          cpus: "1.1"
          memory: "500MB"

# 1.5 CPU, 550MB total
#
#
#
# "Não pensem que vim trazer paz à terra; não vim trazer paz, mas espada. 
# Pois vim para fazer que ‘o homem fique contra seu pai,
#   a filha contra sua mãe, a nora contra sua sogra; 
# os inimigos do homem serão os da sua própria família’.
# "Quem ama seu pai ou sua mãe mais do que a mim não é digno de mim;
#   quem ama seu filho ou sua filha mais do que a mim não é digno de mim; 
#
# Jesus Cristo fora de contexto (?)
